[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "CmE7pzV3xp823iF8z2YEMXXTN8LBwMfBFh3AwDG4V7E9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whale/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
